1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [1]:
import numpy as np

In [7]:
#1
arr=np.random.randint(1,100,size=(3,3),dtype='int')
print(arr)
print(arr.T)# Rows and columns interchange.

[[43 41  1]
 [81 79 53]
 [59 73 77]]
[[43 81 59]
 [41 79 73]
 [ 1 53 77]]


In [10]:
#2
arr=np.arange(10)
print(arr)
print(arr.reshape((2,5)))
print(arr.reshape((5,2)))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [21]:
#3
arr=np.random.rand(4,4)
arr
# To apply border we use pad function. 
np.pad(arr,pad_width=1,constant_values=0)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.12847172, 0.29668358, 0.77148419, 0.01075094,
        0.        ],
       [0.        , 0.30630786, 0.07271655, 0.57842906, 0.17956283,
        0.        ],
       [0.        , 0.84203046, 0.7841867 , 0.57834436, 0.96669721,
        0.        ],
       [0.        , 0.21222559, 0.51356163, 0.64847479, 0.84052832,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [23]:
#4.
arr=np.arange(10,60,5)
arr
arr.reshape(())

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [5]:
#5
arr=np.array(['python', 'numpy', 'pandas'])
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.title(arr))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [6]:
#6
arr_strings=arr
np.char.join(' ',arr_strings)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [10]:
#7
arr_1=np.array([[1,2],[3,4]])
arr_2=np.array([[5,6],[4,5]])
add=np.add(arr_1,arr_2)
subtract=np.subtract(arr_1,arr_2)
multiply=np.multiply(arr_1,arr_2)
divide=np.divide(arr_1,arr_2)
print(add)
print(subtract)
print(multiply)
print(divide)

[[6 8]
 [7 9]]
[[-4 -4]
 [-1 -1]]
[[ 5 12]
 [12 20]]
[[0.2        0.33333333]
 [0.75       0.8       ]]


In [13]:
#8
identity = np.eye(5)
print(identity)
print(np.diagonal(identity))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [32]:
#9
arr_3=np.random.randint(0,1001,100)
arr_3


def is_prime(a):

    if a<2:
        return True
    if a>2:
        for i in range(2,a):
            if a%i==0:
                return True
        return False
                
                

prime_numbers=[]

for i in range(0,len(arr_3)):
    if is_prime(arr_3[i])==True:
        continue
    if is_prime(arr_3[i])==False:
        prime_numbers.append(arr_3[i])
        
prime_numbers

[157,
 491,
 911,
 647,
 71,
 829,
 521,
 43,
 991,
 59,
 101,
 211,
 751,
 283,
 59,
 727,
 673,
 73,
 599,
 421,
 953]

In [33]:
#10
daily_temp=np.random.randint(20,40,size=28)
weekly_average=np.reshape(daily_temp,(4,7)).mea

array([29, 35, 39, 24, 25, 39, 26, 37, 32, 21, 36, 30, 36, 34, 39, 21, 29,
       27, 34, 25, 24, 33, 34, 20, 24, 33, 22, 24])